services:
  smartling.settings:
    class:              Drupal\smartling\Settings\SmartlingSettingsHandler

  smartling.log:
    class:              Drupal\smartling\Log\SmartlingLog

  smartling.api_wrapper:
    class:              Drupal\smartling\ApiWrapper\SmartlingApiWrapper
    arguments:          [@smartling.settings, @smartling.log]

  smartling.local_api_wrapper:
    class:              Drupal\smartling\ApiWrapper\SmartlingLocalApiWrapper
    arguments:          [@smartling.settings, @smartling.log]

  smartling.mock_api_wrapper:
    class:              Drupal\smartling\ApiWrapper\MockApiWrapper
    arguments:          [@smartling.settings, @smartling.log]

  smartling.field_processor_factory:
    class:              Drupal\smartling\FieldProcessorFactory
    arguments:          [%field_processors%, @smartling.log, @smartling.api_wrapper]

  smartling.entity_processor_factory:
    class:              Drupal\smartling\EntityProcessorFactory
    arguments:          [%entity_processors%, @smartling.field_processor_factory, @smartling.log, @smartling.api_wrapper]




  smartling.forms.admin_node_translation_settings:
    class:              Drupal\smartling\Forms\AdminNodeTranslationSettingsForm

  smartling.forms.admin_taxonomy_translation_settings:
    class:              Drupal\smartling\Forms\AdminTaxonomyTranslationSettingsForm

  smartling.forms.admin_entities_translation_settings:
    class:              Drupal\smartling\Forms\AdminEntitiesTranslationSettingsForm

  smartling.forms.admin_account_info_settings:
    class:              Drupal\smartling\Forms\AdminAccountInfoSettingsForm

  smartling.forms.admin_log_info_settings:
    class:              Drupal\smartling\Forms\AdminLogInfoSettingsForm



  smartling.forms.node_settings:
    class:              Drupal\smartling\Forms\NodeSettingsForm

  smartling.forms.comment_settings:
    class:              Drupal\smartling\Forms\CommentSettingsForm

  smartling.forms.taxonomy_term_settings:
    class:              Drupal\smartling\Forms\TaxonomyTermSettingsForm

  smartling.forms.user_settings:
    class:              Drupal\smartling\Forms\UserSettingsForm

  smartling.forms.generic_entity_settings:
    class:              Drupal\smartling\Forms\GenericEntitySettingsForm


parameters:
  entity_processors:
    node:                   Drupal\smartling\Processors\NodeProcessor
    taxonomy_term:          Drupal\smartling\Processors\TaxonomyTermProcessor
    generic:                Drupal\smartling\Processors\GenericEntityProcessor

  field_processors:
    real:
      text:                 Drupal\smartling\FieldProcessors\TextFieldProcessor
      text_long:            Drupal\smartling\FieldProcessors\TextFieldProcessor
      text_with_summary:    Drupal\smartling\FieldProcessors\TextSummaryFieldProcessor
      image:                Drupal\smartling\FieldProcessors\ImageFieldProcessor
      field_collection:     Drupal\smartling\FieldProcessors\FieldCollectionFieldProcessor

    fake:
      title_property:       Drupal\smartling\FieldProcessors\TitlePropertyFieldProcessor
      title_property_field: Drupal\smartling\FieldProcessors\TitlePropertyFieldProcessor
      description_property_field: Drupal\smartling\FieldProcessors\DescriptionPropertyFieldProcessor
      name_property_field:  Drupal\smartling\FieldProcessors\NamePropertyFieldProcessor
